version: '3.3'

services: 
  http-server:
    container_name: http-server
    build: .
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./src:/var/www/html
    links:
    - db
  db:
    container_name: mysql-server
    image: mysql:5.7
    ports:
    - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=root
volumes:
  mysql-data: